### ISSUE TITLE
Post 100% sponsored by Rossi CEO

### ISSUE THREAD

**Issue by David-Lazaro-Fernandez** [JocelynVelarde/LinceHacks2024#1]
## ROSSI CEO 

![image](https://github.com/JocelynVelarde/LinceHacks2024/assets/57787993/f3b069a5-d1c4-4ddf-9254-76a726c35999)

**Comment by JocelynVelarde** [comment]
👀

**Comment by Diego785xd** [comment]
ajjajajajjaj
